namespace Gee.External.Capstone {
    /// <summary>
    ///     Native Disassembler Option Type.
    /// </summary>
    internal enum NativeDisassemblerOptionType {
        /// <summary>
        ///     Indicates no option should be set.
        /// </summary>
        None = 0,

        /// <summary>
        ///     Represents an option to set the syntax of the assembly code generated by a disassembler.
        /// </summary>
        SetSyntax,

        /// <summary>
        ///     Represents an option to set whether a disassembler should generate details when disassembling
        ///     instructions.
        /// </summary>
        SetInstructionDetails,

        /// <summary>
        ///     Represents an option to set a disassembler's disassemble mode.
        /// </summary>
        SetDisassembleMode,
        SetMemory,
        SetSkipData,
        SetSkipDataConfig,
        SetMnemonic,
        SetUnsigned
    }
}