name: PR Workflow
on:
  pull_request:
    branches:
      - *
      - !master
jobs:
  linux:
    name: Linux Job (PR Workflow)
    defaults:
      run:
        shell: bash
        working-directory: .
    runs-on: ubuntu-20.04
    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v2
  
  mac:
    name: MacOS Job (PR Workflow)
    defaults:
      run:
        shell: bash
        working-directory: .
    runs-on: macos-11
    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v2

  windows:
    name: Windows Job (PR Workflow)
    defaults:
      run:
        shell: bash
        working-directory: .
    runs-on: windows-2019
    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v2